# Generated by Django 6.0.6 on 2026-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Mi Gran Evento', max_length=100, verbose_name='Nombre del Evento')),
            ],
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Invitado'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='table_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mesa'),
        ),
    ]
