# Generated by Django 6.0.6 on 2026-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventsetting_eventphoto_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventphoto',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Foto del evento', 'verbose_name_plural': 'Fotos del evento'},
        ),
        migrations.AlterModelOptions(
            name='eventsetting',
            options={'verbose_name': 'Configuración del evento', 'verbose_name_plural': 'Configuración del evento'},
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Aprobada'),
        ),
    ]
